export {default as Home} from './pages/Home'
export {default as Projects} from './pages/Projects'
export {default as About} from './pages/About'
export {default as SignIn} from './pages/SignIn'
export {default as SignUp} from './pages/SignUp'
export {default as Header} from './components/Header'
export {default as FooterCom} from './components/FooterCom'